### ISSUE TITLE
IndexError: index out of range in self

### ISSUE THREAD

**Issue by CaiJichang212** [fc2869/lo-fit#1]
code:
```bash
model_name=Llama-2-7b-hf
echo $HUGGINGFACE_CACHE$model_name
task="clutrr";
seed=42;
python lofit_trainer.py \
    --task $task \
    --base_model_name $HUGGINGFACE_CACHE$model_name \
    --apply_chat_template False \
    --ft_method lofit \
    --lofit_component A \
    --use_topk_heads 160 \
    --lr 5e-4 \
    --train_batch 8 \
    --num_epoch 5 \
    --output_dir "./finetuned_checkpoints/${task}/${model_name}_${task}_Aonly_seed${seed}"\
    --run_mode train \
    --output_file_name "./finetuned_outputs/${task}/${model_name}_${task}_Aonly_seed${seed}"\
    --applied_module attention \
    --save_strategy no \
    --l1_lambda 5e-3 \
    --eval_batch 32 \
    --train_size 300 \
    --seed $seed \
```
bug:
> Traceback (most recent call last):
  File "LoFiT/lofit_trainer.py", line 294, in <module>
    trainer.train(
  File "trl/trainer/sft_trainer.py", line 360, in train
    output = super().train(*args, **kwargs)
  File "transformers/trainer.py", line 1780, in train
    return inner_training_loop(
  File "transformers/trainer.py", line 2118, in _inner_training_loop
    tr_loss_step = self.training_step(model, inputs)
  File "transformers/trainer.py", line 3036, in training_step
    loss = self.compute_loss(model, inputs)
  File "LoFiT/utils/trainers.py", line 49, in compute_loss
    outputs = model(**inputs)
  File "torch/nn/modules/module.py", line 1532, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
  File "torch/nn/modules/module.py", line 1541, in _call_impl
    return forward_call(*args, **kwargs)
  File "LoFiT/models/modeling_llama.py", line 847, in forward
    outputs = self.model(
  File "torch/nn/modules/module.py", line 1532, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
  File "torch/nn/modules/module.py", line 1541, in _call_impl
    return forward_call(*args, **kwargs)
  File "LoFiT/models/modeling_llama.py", line 667, in forward
    inputs_embeds = self.embed_tokens(input_ids)
  File "torch/nn/modules/module.py", line 1532, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
  File "torch/nn/modules/module.py", line 1541, in _call_impl
    return forward_call(*args, **kwargs)
  File "torch/nn/modules/sparse.py", line 163, in forward
    return F.embedding(
  File "torch/nn/functional.py", line 2264, in embedding
    return torch.embedding(weight, input, padding_idx, scale_grad_by_freq, sparse)
IndexError: index out of range in self

**Comment by CaiJichang212** [comment]
![image](https://github.com/fc2869/lo-fit/assets/167088965/30081293-c165-4d42-8629-ac72c6b875d8)

> torch.Size([8, 120])
torch.Size([32001, 4096])

**Comment by fc2869** [comment]
Thank you for your interest in our work! 

It looks like there might be some issues related to the vocabulary after adding the pad_token as defined in:
https://github.com/fc2869/lo-fit/blob/39c2d587652c0c74a3128924707cc86359fb5530/lofit_trainer.py#L166-L168

Could you please print out the token ids of the padding token, begin-of-sentence, and end-of-sentence token for the debugging purpose? Thanks!
```
print(tokenizer.convert_tokens_to_ids('[PAD]'))
print(tokenizer.convert_tokens_to_ids(tokenizer.eos_token))
print(tokenizer.convert_tokens_to_ids(tokenizer.bos_token))
```

**Comment by CaiJichang212** [comment]
Thank you very much for your prompt answer. It's very kind of you. Your work is very inspiring to me and I will cite your paper.
![image](https://github.com/fc2869/lo-fit/assets/167088965/ffa52ead-b52b-4094-8324-5c02100a1ad3)

> tokenizer.pad_token
32001
2
1

![image](https://github.com/fc2869/lo-fit/assets/167088965/3a95f47c-da7b-4289-a797-9ce036725c03)

> inputs_embeds
torch.Size([8, 120])
torch.Size([32001, 4096])

new bug,It is caused by the same reason as `IndexError: index out of range in self`,I guess.
> Traceback (most recent call last):
  File "LoFiT/lofit_trainer.py", line 299, in <module>
    trainer.train(
  File "site-packages/trl/trainer/sft_trainer.py", line 360, in train
    output = super().train(*args, **kwargs)
  File "site-packages/transformers/trainer.py", line 1780, in train
    return inner_training_loop(
  File "site-packages/transformers/trainer.py", line 2118, in _inner_training_loop
    tr_loss_step = self.training_step(model, inputs)
  File "site-packages/transformers/trainer.py", line 3036, in training_step
    loss = self.compute_loss(model, inputs)
  File "LoFiT/utils/trainers.py", line 49, in compute_loss
    outputs = model(**inputs)
  File "site-packages/torch/nn/modules/module.py", line 1532, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
  File "site-packages/torch/nn/modules/module.py", line 1541, in _call_impl
    return forward_call(*args, **kwargs)
  File "LoFiT/models/modeling_llama.py", line 851, in forward
    outputs = self.model(
  File "site-packages/torch/nn/modules/module.py", line 1532, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
  File "site-packages/torch/nn/modules/module.py", line 1541, in _call_impl
    return forward_call(*args, **kwargs)
  File "LoFiT/models/modeling_llama.py", line 677, in forward
    attention_mask = self._prepare_decoder_attention_mask(
  File "LoFiT/models/modeling_llama.py", line 601, in _prepare_decoder_attention_mask
    combined_attention_mask = _make_causal_mask(
  File "LoFiT/models/modeling_llama.py", line 49, in _make_causal_mask
    mask = torch.full((tgt_len, tgt_len), torch.finfo(dtype).min, device=device)
RuntimeError: CUDA error: device-side assert triggered
CUDA kernel errors might be asynchronously reported at some other API call, so the stacktrace below might be incorrect.
For debugging consider passing CUDA_LAUNCH_BLOCKING=1.
Compile with `TORCH_USE_CUDA_DSA` to enable device-side assertions.
![image](https://github.com/fc2869/lo-fit/assets/167088965/bebc962b-6b06-462c-9521-d43f05fcb591)

**Comment by fc2869** [comment]
You are very welcome! We really appreciate your feedback :)
I noticed that the id of the padding token `'[PAD]' `is `32001` as shown in the first screenshot; it should be `32000` as the last index of the vocabulary that has a size of 32001 after resizing. It might lead to the index out of the range error and the failed assertion as `32001` is out of range for the given vocab size. 
This is weird as I got `32000` on my local run using the same code snippet. Would you mind checking the vocab size of the tokenizer in the model config and the tokenizer itself before adding the padding token (i.e. before line 167 in lofit_trainer.py) with the following print statements?
```
print(model.config.vocab_size)
print(len(tokenizer))
```
They should be both `32000` before adding the padding token. If not, maybe there are some issues with the llama 2-7b huggingface vocab config. It could be a legacy issue as mentioned here: https://github.com/huggingface/transformers/issues/24899 If this is the case, you can try re-downloading the llama-2-7b-hf checkpoint as suggested by one of the comments in this issue.

Hopefully this helps, let me know if there are any further questions!

**Comment by CaiJichang212** [comment]
Thank you very much for your help in finding the cause of the bug.
![image](https://github.com/fc2869/lo-fit/assets/167088965/1930cbf4-8f36-42fe-856c-88e408207bb7)

> 32000
32001
tokenizer.pad_token
32001
2
1

From the output, as you can guess, I need to consider redownloading the llama2-7b weights file.

**Comment by fc2869** [comment]
You are welcome! Feel free to reach out if there are any other questions :)
