### ISSUE TITLE
An inquiry about GPU resource.

### ISSUE THREAD

**Issue by SydCS** [fc2869/lo-fit#2]
Hello,
Thank you very much for your excellent work!
Given the constraints of my available resources, I currently have only a few 4090 GPUs with 24GB of memory each. Attempting to train the model on a single GPU results in OOM. I am considering multi-GPU training as a solution. Could you advise if this approach is feasible with the current setup?
Additionally, I would like to inquire about the tuned head scales and biases. Would it be acceptable to release these weights?
Thank you in advance for your guidance.

**Comment by fc2869** [comment]
Hi, thank you for your interest in our work! If you are training the 7b models, you can use bfloat16 training rather than the full precision training by changing the following blocks in `lofit_trainer.py`:
https://github.com/fc2869/lo-fit/blob/9d8a629edc87c911edc5917026d9793cb35d1487/lofit_trainer.py#L142C1-L144C17
to:
```
else:
    torch_dtype = torch.bfloat16
    bf16 = True
```
I briefly tested this on llama2 7b with an NVIDIA A40 48GB GPU and it only used 19GB GPU memory. Hopefully it would also fit the 24GB memory of 4090 GPU. Let me know if this works for you.

Regarding the tuned head scales and biases, yes we do have a plan to release them! We are still looking at how to integrate them with huggingface. Please stay tuned :)

**Comment by SydCS** [comment]
Thank you for this answer!
Unfortunately, when running llama2_7B, changing it to BF16 still results in OOM ( •̥́ ˍ •̀)
In float32, OOM occurs when `trainer = trainer(...)`. In bfloat16, OOM occurs when `trainer.train()`.
Is there any another possible fix?
Also, looking forward to this framework to be compatible with Llama3.2 series. So that I can try to tune the 3B version instead.

**Comment by fc2869** [comment]
I am sorry to hear that :( When using bfloat16, have you tried using a smaller batch size and gradient accumulation? If that doesn't work either, I will look into multi-GPU implementations and get back to you later. And yes, we will have support for Llama3.2/3.3 series soon!

**Comment by fc2869** [comment]
@SydCS Hi, I appreciate your interest in our work again! Just to let you know that we release the weights of fine-tuned models that integrate the tuned biases here: 
https://huggingface.co/fcyin/llama2_7B_base_lofit_mquake
https://huggingface.co/fcyin/llama2_7B_base_lofit_truthfulqa
You can use these weights and the code snippets included in the hugging face repo to run evaluations. Let me know if you have encountered issues when using these weights :)

**Comment by SydCS** [comment]
Thank you for this open source！

When I evaluate on truthfulQA, a bug occurs:
```
Traceback (most recent call last):
  File "eval_truthfulqa.py", line 27, in <module>
    evaluate_tqa(fname='./',eval_dataset = dataset['test'],model_name = model_name,metrics=['mc'],tokenizer=tokenizer,model=model)
  File "/root/autodl-fs/lo-fit/utils/evaluate.py", line 84, in evaluate_tqa
    curr_fold_results = alt_tqa_evaluate(
  File "/root/autodl-fs/lo-fit/honest_llama/utils.py", line 651, in alt_tqa_evaluate
    ce_loss = run_ce_loss(model_key, model=llama_model, tokenizer=llama_tokenizer, device=device, interventions=interventions, intervention_fn=intervention_fn)
  File "/root/autodl-fs/lo-fit/honest_llama/utils.py", line 416, in run_ce_loss
    dataset = load_dataset("stas/openwebtext-10k")['train']
  File "/root/miniconda3/envs/lofit/lib/python3.8/site-packages/datasets/load.py", line 2556, in load_dataset
    builder_instance = load_dataset_builder(
  File "/root/miniconda3/envs/lofit/lib/python3.8/site-packages/datasets/load.py", line 2228, in load_dataset_builder
    dataset_module = dataset_module_factory(
  File "/root/miniconda3/envs/lofit/lib/python3.8/site-packages/datasets/load.py", line 1879, in dataset_module_factory
    raise e1 from None
  File "/root/miniconda3/envs/lofit/lib/python3.8/site-packages/datasets/load.py", line 1831, in dataset_module_factory
    can_load_config_from_parquet_export = "DEFAULT_CONFIG_NAME" not in f.read()
  File "/root/miniconda3/envs/lofit/lib/python3.8/codecs.py", line 322, in decode
    (result, consumed) = self._buffer_decode(data, self.errors, final)
UnicodeDecodeError: 'utf-8' codec can't decode byte 0xb5 in position 1: invalid start byte
```

Has this ever happened to you?

**Comment by fc2869** [comment]
Hi, I couldn't reproduce the issue above on my machine, and I suspect it might be something related to the `datasets` library that made it unable to load `stas/openwebtext-10k.` 

I was looking up the issue. It seemed that if you were running the code in an environment where you need VPN to access huggingface, the issue should be fixed once you have the VPN on. (https://github.com/horseee/LLM-Pruner/issues/77) Otherwise, you can try downgrade the version of datasets as mentioned in the last comment of the github issue above as well.

If none of these work, you might consider the following brute-force fix: ignoring the evaluation on openwebtext. We didn't use it as part of our evaluation because it is just a measure of perplexity and it is not our main focus for truthfulness. To do that you can simply comment out all the following lines of code:

```
if 'llama' in model_key or 'alpaca' in model_key or 'vicuna' in model_key or 'gemma' in model_key:
            ce_loss = run_ce_loss(model_key, model=llama_model, tokenizer=llama_tokenizer, device=device, interventions=interventions, intervention_fn=intervention_fn)
            # kl_wrt_orig = run_kl_wrt_orig(model_key, model=llama_model, tokenizer=llama_tokenizer, device=device, interventions=interventions, intervention_fn=intervention_fn, separate_kl_device=separate_kl_device)
        kl_wrt_orig = 0
        results.loc[model_key, 'CE Loss'] = ce_loss
        results.loc[model_key, 'KL wrt Orig'] = kl_wrt_orig
```
It won't affect the truthfulness evaluation results (MC1, MC2).
Let me know if there is still any problem running the evaluation code.

**Comment by SydCS** [comment]
It helped a lot.
Thank you for these responses!
